### ISSUE TITLE
`org.openjfx:javafx-base:13-ea+8` and friends are not detected by this tool

### ISSUE THREAD

**Issue by rotty3000** [sormuras/modules#2]
See https://repo1.maven.org/maven2/org/openjfx/javafx-base/13-ea+8/

**Comment by sormuras** [comment]
What does the module name of this artifact look like? (on my mobile, atm)

**Comment by sormuras** [comment]
`javafx.base`, right?

At least I used it and two friends here with those module names: https://github.com/sormuras/bach/tree/master/demo/javafx

The module names don't start with their artifacts Maven Group Id `org.openjfx` -- thus, the default filter won't select those modules. See more details at the root README.md file.

But, I can map "org.openjfx" to "javafx". Is this officially _true_ and correct?

**Comment by rotty3000** [comment]
`javafx.base`

But note that there are classifier artifacts associated which are the real modules.

**Comment by rotty3000** [comment]
I am not a committer on that project, but I _believe_ these are the new _official_ javafx artifacts.

**Comment by sormuras** [comment]
Looks good: https://openjfx.io/openjfx-docs/#maven -- adding the alias in a minute and rebuild the database.

fwiw, http://openjfx.org does not look good.

**Comment by rotty3000** [comment]
I think this is the real site https://openjfx.io/ :) but you're right that other one looks creepy generated ad site.

**Comment by rotty3000** [comment]
FYI, I wanted to show these more as examples of things not being discovered by the scan.

**Comment by sormuras** [comment]
### From
Collected 4,253 unique modules.
  automatic :cd: -> 3,300
  explicit :dvd: -> 953
  
### To
Collected 4,261 unique modules.
  automatic :cd: -> 3,308
  explicit :dvd: -> 953

8 "new" automatic modules found. Thanks for the hint.

If you know modules not listed here yet, just let me know. A hand-selected alias file for official exception to the rule is fine for me.
